config/routes.rb
Rails.application.routes.draw do
  get 'temporary_uploads/index'
  get 'users/edit_playlist'
  root 'sessions#login_page'

  get 'home' => 'users#index'
  post 'users/create_playlist'
  get 'users/edit_playlist'
  post 'users/edit_playlist'
  post 'users/upload_song'
  post 'users/upload_song_successfully'
  get 'users/download_song_url_for'
  get 'users/change_playlist'
  post 'users/change_playlist'

  get 'login' => 'sessions#login_page'
  post 'login' => 'sessions#login'

  get 'logout' => 'sessions#logout'

  get 'signup' => 'sessions#signup_page'
  post 'signup' => 'sessions#signup'

  get 'login_error' => 'sessions#login_page_error'
  get 'signup_error' => 'sessions#signup_page_error'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  has_many :songs
  accepts_nested_attributes_for :songs

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :playlist

end

app/models/temp_upload.rb
class TempUpload < ActiveRecord::Base
    
     mount_uploader :song, SongUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :playlists

  def self.create_user(name, username, password, password_confirm)
    return false if password != password_confirm
    return false if User.where(username: username).to_a.size > 0

    salt = BCrypt::Engine.generate_salt
    hashed_password = BCrypt::Engine.hash_secret(password, salt)
    new_user = User.create(name: name, username: username, password: hashed_password, salt: salt)
    new_user
  end

  def self.authenticate(username, password)
    user = User.where(username: username).first
    if user.present? && user.password == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Configuration for AWS-SDK
  client = Aws::S3::Client.new(
      access_key_id: 'AKIAJYEZOQ7YSKG5GSCQ',
      secret_access_key: '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',
      region: 'ap-southeast-1'
  )

  RESOURCE = Aws::S3::Resource.new(client: client)
  BUCKET_NAME =  "profswd-song-storage"

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except: :logout

  def login_page
    if session[:user_id]
      redirect_to home_path
    end
  end

  def login
    if (params[:username] != "" && params[:password] != "")
      user = User.authenticate(params[:username], params[:password])
    end
    if user
      session[:user_id] = user.id
      redirect_to
    else
#      redirect_to action: :login_page
      redirect_to action: :login_page_error
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to action: :login_page
  end

  def signup
    if (params[:name] != "" && params[:username] != "" && params[:password] != "" && params[:cpassword] != "")
      user = User.create_user(params[:name], params[:username], params[:password], params[:cpassword])
    end
    if user
      redirect_to action: :login
    else
#      redirect_to action: :signup
      redirect_to action: :signup_page_error
    end
  end
end

app/controllers/users_controller.rb
# Global Variables
$key = 'initialize'

class UsersController < ApplicationController
  before_action :require_login

  def index
    @songs = RESOURCE::bucket(BUCKET_NAME).objects

    user_id = User.where(id: session[:user_id]).first
    if(!user_id.nil?)
      @name_of_user = user_id.name
    end

    @allPlaylist = Playlist.all
    @session_id = session[:user_id]

    upload_song
    change_playlist
  end

  def create_playlist
    @playlist = Playlist.new
    @playlist.user_id = session[:user_id]
    @playlist.title = params[:playlist_title]
    @playlist.save

    redirect_to home_path
  end

  def change_playlist
    @chosen_playlist_id = params[:my_playlist]
    @playlist_songs = Song.where(:playlist_id => @chosen_playlist_id)

    if(params[:my_playlist].present?)
      @current_playlist = Playlist.where(:id => params[:my_playlist]).first.title
    end
  end

  def edit_playlist
    @ePlaylist = Playlist.find(params[:edit_this_playlist])
    # @ePlaylist.title = params[:edit_playlist_title]
    # @ePlaylist.save
    @ePlaylist.update(title: params[:edit_playlist_title])

    redirect_to home_path
  end

  def upload_song
    @uploader = TempUpload.new.song
    @uploader.success_action_redirect = home_url

    if(params[:key].present?)
      $key = params[:key]
    end
  end

  def upload_song_successfully
    @song = Song.new
    @song.playlist_id = params[:song_playlist]
    @song.title = params[:song_title]
    @song.artist = params[:song_artist]
    @song.key = $key

    if(@song.playlist_id.present? && @song.title.present? && @song.artist.present? && !@song.key.eql?("initialize"))
      @song.save
    end

    redirect_to home_path
  end

  private
  def sanitize_filename(file_name)
    just_filename = File.basename(file_name)
    just_filename.sub(/[^\w\.\-]/,'_')
  end

  private
  def require_login
    redirect_to login_path if session[:user_id].nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Configuration for AWS-SDK
  client = Aws::S3::Client.new(
      access_key_id: 'AKIAJYEZOQ7YSKG5GSCQ',
      secret_access_key: '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',
      region: 'ap-southeast-1'
  )

  RESOURCE = Aws::S3::Resource.new(client: client)
  BUCKET_NAME =  "profswd-song-storage"

  def download_song_url_for(song_key)
    RESOURCE::bucket(BUCKET_NAME).object(song_key).public_url
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicPlayerV3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit_playlist.html.erb
<h1>Users#edit_playlist</h1>
<p>Find me in app/views/users/edit_playlist.html.erb</p>

app/views/users/index.html.erb
<body id="page-top" class="index">
  <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#page-top">OPUS1</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li class="hidden">
              <a href="#page-top"></a>
            </li>
            <li class="page-scroll">
              <a href="#" data-toggle="modal" data-target="#create-playlist-modal">Create Playlist</a>
            </li>
            <li class="page-scroll">
              <a href="#" data-toggle="modal" data-target="#edit-playlist-modal">Edit Playlist</a>
            </li>
            <li class="page-scroll">
              <a href="#" data-toggle="modal" data-target="#upload-song-modal">Upload Track</a>
            </li>
            <li class="page-scroll">
              <a href="#" data-toggle="modal" data-target="#add-to-playlist-modal">Add To Playlist</a>
            </li>
            <li class="page-scroll">
              <!--<a href="#username">Username</a>-->
              <% if @name_of_user.present? %>
                <a href="#"> <%= @name_of_user %> </a>
              <% end %>
            </li>
            <li class="page-scroll">
              <%= link_to "Logout", controller: 'sessions', action: 'logout' %>
            </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
    <!-- /.container-fluid -->
    </nav>

    <!-- Header -->
    <header>
      <div class="container">
        <div class="row">
          <div class="col-lg-offset-0">
            <!--<img class="img-responsive" src="img/profile.png" alt="">-->
            <!--<div class="intro-text">-->
              <!--<span class="name">Play Your Beat</span>-->
              <!--<hr class="star-light">-->
              <!--&lt;!&ndash;<span class="skills">Web Developer - Graphic Artist - User Experience Designer</span>&ndash;&gt;-->
            <!--</div>-->
            <div id="shortcuts">
              <div>
                <!--<h1>Keyboard Shortcuts</h1>-->
                <p><em>&rarr;</em> Next Track </p>
                <p><em>&larr;</em> Previous Track </p>
                <p><em>Space</em> Play/Pause </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>


    <!-- Create Playlist -->
    <section class="modal fade" id="create-playlist-modal" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 class="modal-title">Create Playlist</h4>
          </div>
          <%= form_tag(users_create_playlist_path, method: :post, multipart: :true) do %>
          <div class="modal-body">
            <label class="control-label" for="playlist-title">Title</label>
            <%= text_field_tag "playlist_title", nil, class: 'form-control', placeholder: 'Title', id: 'playlist-title'  %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <%= submit_tag "Create", class: 'btn btn-primary'%>
          </div>
          <% end %>
        </div>
      </div>
    </section>

  <!-- Edit Playlist -->
  <section class="modal fade" id="edit-playlist-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title">Edit Playlist</h4>
        </div>

        <%= form_tag(users_edit_playlist_path, method: :post) do %>
          <div class="modal-body" id="edit-playlist-form">
            <div class="form-group">
              <label for="select" class="control-label">Playlist</label>
              <% if @allPlaylist.nil? %>
                <select class="form-control" id="select">
                  <option>No Available Playlist</option>
                </select>
              <% else %>
                <%= select_tag("edit_this_playlist",
                               options_from_collection_for_select(Playlist.where(user_id: @session_id), :id, :title),
                               class: 'form-control'
                    )
                %>
              <% end %>
              <br/>
              <label class="control-label" for="playlist-title">New Playlist Title</label>
              <%= text_field_tag "edit_playlist_title", nil, class: 'form-control', id: 'playlist-title', placeholder: 'New Playlist Title' %>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <%= submit_tag "Save", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
      </div>
  </section>


  <!-- Upload Song -->
  <section class="modal fade" id="upload-song-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title">Upload Track</h4>
        </div>

        <%= direct_upload_form_for @uploader do |f| %>
          <div class="modal-body">
            <label class="control-label" for="song-file">Track</label>
            <%= f.file_field :song, class: 'btn btn-success', id: 'song-file' %>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <%= f.submit "Upload", class: 'btn btn-primary', id: 'upload-song-btn' %>
          </div>
        <% end %>
      </div>
    </div>
  </section>

  <!-- Add To Playlist -->
  <section class="modal fade" id="add-to-playlist-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title">Add To Playlist</h4>
        </div>

        <%= form_tag(users_upload_song_successfully_path, method: :post, multipart: :true) do %>
          <div class="modal-body" id="song-info-form">
            <div class="form-group">
              <label for="select" class="control-label">Playlist</label>
              <% if @allPlaylist.nil? %>
                <select class="form-control" id="select">
                  <option contenteditable="false">No Available Playlist</option>
                </select>
              <% else %>
                <%= select_tag("song_playlist",
                               options_from_collection_for_select(Playlist.where(user_id: @session_id), :id, :title),
                               class: 'form-control'
                    )
                %>
              <% end %>
              <br/>
              <label class="control-label" for="song-title">Title</label>
              <%= text_field_tag "song_title", nil, class: 'form-control', id: 'song-title', placeholder: 'Title' %>
              <br/>
              <label class="control-label" for="song-artist">Artist</label>
              <%= text_field_tag "song_artist", nil, class: 'form-control', id: 'song-artist', placeholder: 'Artist' %>
              <br/>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <%= submit_tag "Save", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </section>


  <section id="music-player">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2>OPUS1 Playlists</h2>
          <hr class="star-primary">
        </div>
      </div>

      <div class="row">
        <!--<div class="col-lg-10">-->
        <%= form_tag(home_path, method: :get) do %>
          
          <div class="modal-body">
            <div class="form-group text-center">
              <!--<label for="select" class="control-label">Playlist</label>-->
              <% if @allPlaylist.nil? %>
                <select class="form-control" id="select">
                  <option contenteditable="false">No Available Playlist</option>
                </select>
              <% else %>
                <%= select_tag("my_playlist", options_from_collection_for_select(Playlist.where(user_id: @session_id), :id, :title), class: 'form-control') %>
              <% end %>
            </div>
            <div class="modal-header">
              <%= submit_tag "Load Playlist", class: 'btn btn-primary' %>
            </div>
          </div>
          <!--<p class="help-block text-danger"></p>-->
        <% end %>
      </div>

      <!--<div class="row">-->
      <!--<audio preload></audio>-->
      <!--<% if @playlist_songs.nil? %>-->
        <!--<p>No songs added.</p>-->
        <!--<% else %>-->
        <!--<ol id="list">-->
        <!--<% @playlist_songs.each do |song| %>-->
          <!--<li id="tracks"><%= link_to song.title <<  " | " << song.artist, '#',  data: {src: download_song_url_for(song.key)} %></li>-->
          <!--<% end %>-->
        <!--</ol>-->
        <!--<% end %>-->
      <!--</div>-->

      <!--<div id="shortcuts">-->
      <!--<div>-->
      <!--<h1>Keyboard shortcuts:</h1>-->
      <!--<p><em>&rarr;</em> Next track</p>-->
      <!--<p><em>&larr;</em> Previous track</p>-->
      <!--<p><em>Space</em> Play/pause</p>-->
      <!--</div>-->
      <!--</div>-->
    </div>
      </div>
  </section>

  <footer>
    <div class="navbar-brand">
      <div class="col-lg-offset-11">
        <div class="row">
          <ol id="list">
            <% if @current_playlist.present? %>
              <p style="color:#2c3e50"><%= @current_playlist %> </p>
            <% else %>
              <p style="color:#2c3e50">No Playlist Chosen</p>
            <% end %>

            <% if @playlist_songs.present? %>
              <% @playlist_songs.each do |song| %>
                <li id="tracks" class="list-group-item success"><%= link_to song.title, '#',  data: {src: download_song_url_for(song.key)} %></li>
            <% end %>
            <% else %>
              <li id="tracks" class="list-group-item success">No songs added.</li>
            <% end %>
          </ol>
        </div>
      <audio preload/>
      </div>
    </div>
  </footer>
</body>

app/views/users/upload_song.html.erb
<h1>Users#upload_song</h1>
<p>Find me in app/views/users/upload_song.html.erb</p>

app/views/users/upload_song_successfully.html.erb
<h1>Users#upload_song_successfully</h1>
<p>Find me in app/views/users/upload_song_successfully.html.erb</p>